var b = new Boolean(0);
Io.print((typeof b )+ "\n");
Io.print((b.toString() )+ "\n");
var n = new Number(3);
Io.print((typeof n )+ "\n");
Io.print((n.toString() )+ "\n");
var s = new String("hi");
Io.print((typeof s )+ "\n");
Io.print((s.toString() )+ "\n");
var o = new Object();
Io.print((o.toString() )+ "\n");
var a = new Array(1, 2);
Io.print((a.toString() )+ "\n");
