var b = new Boolean(0);
Io.print(typeof b);
Io.print(b.toString());
var n = new Number(3);
Io.print(typeof n);
Io.print(n.toString());
var s = new String("hi");
Io.print(typeof s);
Io.print(s.toString());
var o = new Object();
Io.print(o.toString());
var a = new Array(1, 2);
Io.print(a.toString());
