Io.print(Math.abs(-3));
Io.print(Math.floor(1.9));
Io.print(Math.ceil(1.1));
Io.print(Math.max(1, 5, 2));
Io.print(Math.min(1, 5, 2));
Io.print(Math.pow(2, 3));
Io.print(Math.sqrt(9));
Io.print(Date(0));
var d = new Date(0);
Io.print(d.toString());
Io.print(d.valueOf());
var r = new RegExp("ab", "gi");
Io.print(r.toString());
Io.print(r.source);
Io.print(r.global);
Io.print(r.ignoreCase);
