var s = new String("hello");
Io.print(s.slice(1, 4));
Io.print(s.slice(-2));
Io.print(s.slice(1, -1));
var a = new Array(1, 2);
var c = a.concat(new Array(3), 4);
Io.print(c.toString());
var n = new Number(2.5);
Io.print(n.toFixed(0));
var m = new Number(-2.5);
Io.print(m.toFixed(0));
var z = new Number(-0);
Io.print(z.toFixed(2));
