var s = new String("hello");
var nan = 0/0;
Io.print(s.slice(0, 100));
Io.print(s.slice(10));
Io.print(s.slice(nan, 2));
Io.print(s.slice(2, nan));
Io.print(s.substring(0, 100));
Io.print(s.substring(10));
Io.print(s.substring(nan, 2));
Io.print(s.substring(2, nan));
var e = new String("");
Io.print(e.slice(0, 1));
Io.print(e.substring(0, 1));
