Io.print(Number("  42 "));
Io.print(Number(""));
Io.print(Number("   "));
Io.print(Number("0x10"));
Io.print(Number("+0x10"));
Io.print(Number("-0x10"));
var n1 = Number("0x");
Io.print(n1 != n1);
var n2 = Number("10px");
Io.print(n2 != n2);
Io.print(Number("1e2"));
var n3 = Number("1e");
Io.print(n3 != n3);
var inf = Number("Infinity");
Io.print(inf > Number("1e308"));
var ninf = Number("-Infinity");
Io.print(ninf < Number("-1e308"));
var n4 = Number("NaN");
Io.print(n4 != n4);
