Io.print(Number(".5"));
Io.print(Number("1."));
Io.print(Number("1e+2"));
Io.print(Number("1e-2"));
var n1 = Number("1e");
Io.print(n1 != n1);
var n2 = Number("1e+");
Io.print(n2 != n2);
var n3 = Number("inf");
Io.print(n3 != n3);
var n4 = Number("nan");
Io.print(n4 != n4);
var n5 = Number("1 2");
Io.print(n5 != n5);
var n6 = Number("+");
Io.print(n6 != n6);
var n7 = Number("-");
Io.print(n7 != n7);
var pinf = Number("+Infinity");
Io.print(pinf > Number("1e308"));
var ninf = Number("-Infinity");
Io.print(ninf < Number("-1e308"));
var n8 = Number("0x");
Io.print(n8 != n8);
